Bruno branch
ceelogre/collabo pull request #8
Opened 2020-09-09 11:50 UTC by KundwaBruno

BrunoBranch added changes to <h1> element style

2020-09-10 10:17 UTC, ceelogre requested changes
Solve conflicting files `index.css` and `index.html`

2020-09-10 12:09 UTC, KundwaBruno commented
Thank you... I just resolved the conflicting files.
There are no other conflicting files mentioned.
Thank you

On Thu, Sep 10, 2020, 12:17 Samuel Nishimwe <notifications@github.com>
wrote:

> *@ceelogre* requested changes on this pull request.
>
> Solve conflicting files index.css and index.html
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ceelogre/collabo/pull/8#pullrequestreview-485787404>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ5IMRV2NRZAJQSMBEALPVTSFCRTXANCNFSM4RCAVNMA>
> .
>

2020-09-11 10:32 UTC, ceelogre approved these changes

2020-09-11 10:35 UTC, 41hulk approved these changes
Great

2020-09-11 10:36 UTC, merged